---
title: "Schulz_Viz_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(DESeq2)
```


```{r}
## Import data

rawcounts <- read.table("18-5-23_dedup_Proc_ibet_TC_for_deseq.txt", header = TRUE)

```

```{r}
## Normalization

rawcounts_norm <- rawcounts

head(rawcounts)

rownames(rawcounts_norm) <- rawcounts_norm$gene

rawcounts_norm <- rawcounts_norm %>% dplyr::select(-gene)

# for coldata with times as numeric

coldata <- data.frame(names = colnames(rawcounts_norm)) %>%
  separate(names, c("treat","time","rep"),"_") %>%
  mutate(time = ifelse(time == "ib", 0, 
                        ifelse(time == "6h", 6, 
                               ifelse(time == "12h", 12,
                                      ifelse(time == "24h", 24,
                                             ifelse(time == "48h", 48,
                                                    ifelse(time == "3d", 72,
                                                           ifelse(time == "7d", 168,
                                                                  ifelse(time == "10d", 240, 336)))))))))
```

```{r}
## Normalization

# converting coldata to factor data (categorical) for contrast

coldata <- data.frame(names = colnames(rawcounts_norm)) %>%
  separate(names, c("treat","time","rep"),"_") %>%
  mutate(timetreat = paste(treat,time,sep = "_")) %>%
  select(-c(treat,time))

rownames(coldata) <- colnames(rawcounts_norm)

dds <- DESeqDataSetFromMatrix(rawcounts_norm,colData = coldata, ~ timetreat)

dds_de <- DESeq(dds)

norm_counts <- as.data.frame(counts(dds_de, normalized = TRUE)) %>%
  mutate(gene = rawcounts$gene)

```


```{r}
## Filter significant results and contrast consecutive times

contrast_vect = c(0, 6,12,24,48,72,168,240,336)
contrast_list <- list()

for (i in 1:8) {
  de_results <- results(dds_de, contrast = c("timetreat", coldata$timetreat[i], coldata$timetreat[i+3]))

  resSig <- de_results[ which(de_results$padj < .05 ), ]

  resSig <- resSig[ which(abs(resSig$log2FoldChange) > 2 ), ]

  resSig$gene <- rownames(resSig)

  ind <- match(norm_counts$gene,resSig$gene)

  norm_counts$sig <- resSig$gene[ind]

  norm_counts_sig <- norm_counts %>%
   filter(!is.na(sig)) %>%
   select(-sig) %>%
   mutate(contrast = contrast_vect[i+1])
  contrast_list[[i]] = norm_counts_sig 
}

norm_counts_contrast_consec <- bind_rows(contrast_list[[1]],contrast_list[[2]],contrast_list[[3]],contrast_list[[4]],contrast_list[[5]],contrast_list[[6]],contrast_list[[7]],contrast_list[[8]])

```

```{r}
## Filter significant results and contrast times from t_0

contrast_vect = c(0, 6,12,24,48,72,168,240,336)
contrast_list <- list()

for (i in 1:8) {
  de_results <- results(dds_de, contrast = c("timetreat", "noo_ib", coldata$timetreat[i+3]))

  resSig <- de_results[ which(de_results$padj < .05 ), ]

  resSig <- resSig[ which(abs(resSig$log2FoldChange) > 2 ), ]

  resSig$gene <- rownames(resSig)

  ind <- match(norm_counts$gene,resSig$gene)

  norm_counts$sig <- resSig$gene[ind]

  norm_counts_sig <- norm_counts %>%
   filter(!is.na(sig)) %>%
   select(-sig) %>%
   mutate(contrast = contrast_vect[i+3])
  contrast_list[[i]] = norm_counts_sig 
}

norm_counts_contrast <- bind_rows(contrast_list[[1]],contrast_list[[2]],contrast_list[[3]],contrast_list[[4]],contrast_list[[5]],contrast_list[[6]],contrast_list[[7]],contrast_list[[8]])
```

```{r}
## Tidy data

counts_gath_norm <- norm_counts_contrast %>%
  gather(-c(gene,contrast), key="sample", value = "rawcount") %>%
  mutate(sample2 = sample) %>%
  separate(sample2, c("treat", "time", "rep"), "_") %>%
  mutate(time = ifelse(time == "ib", 0, 
                        ifelse(time == "6h", 6, 
                               ifelse(time == "12h", 12,
                                      ifelse(time == "24h", 24,
                                             ifelse(time == "48h", 48,
                                                    ifelse(time == "3d", 72,
                                                           ifelse(time == "7d", 168,
                                                                  ifelse(time == "10d", 240, 336)))))))))

counts_sum_norm <- counts_gath_norm %>%
  group_by(contrast, gene, treat, time) %>%
  summarize(avecount = mean(rawcount))

```


```{r}
# filtering for counts with 2 times more at the end than beginning
#counts_sum_norm_2 <- counts_sum_norm %>%
#  group_by(gene) %>%
#  filter(nth(avecount,8) > 2*nth(avecount,9))
```

```{r}
## plots facet wrapped by contrast
counts_sum_norm %>%
  ggplot(aes(x=time, y=avecount, color=gene)) + 
  geom_line(alpha = 0.25) + geom_vline(aes(xintercept=contrast), color = "black") + geom_vline(aes(xintercept = 0),color = "black")+
  #ylim(0,50000) +
  theme(legend.position = "none", panel.background = element_blank(), axis.title = element_text(size = 16)) +
  facet_wrap(~contrast) +
  labs(x = "time (hr)", y = "avg count")

## log transformed plots facet wrapped by contrast
counts_sum_norm %>%
  ggplot(aes(x=time, y=log2(avecount), color=gene)) + 
  geom_line(alpha = 0.25) + geom_vline(aes(xintercept=contrast), color = "black") + geom_vline(aes(xintercept = 0),color = "black")+
  #ylim(0,log2(50000)) +
  theme(legend.position = "none", panel.background = element_blank(), axis.title = element_text(size = 16)) +
  facet_wrap(~contrast) +
  labs(x = "time (hr)", y = expression("log"[2]~"(avg count)"))
```


