---
title: "gsea_edit"
author: "Lian Morales"
date: "7/30/2019"
output: html_document
---

```{r}
#LOADING DESEQ2 AND RNASEQ FILE
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
#BiocManager::install("maSigPro")

library("dplyr")
library("tidyr")
library("DESeq2")
library(readr)
library(devtools)
library("DESeq2")
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library("vsn")
library("hexbin")
library("corrplot")
library(maSigPro)
#for GSEA
library(doParallel)
library(fgsea)
library(BiocParallel)
```
 


 
```{r, include=FALSE}
#DESEQ ON SAVAGE DATA - THREE COMPARISON MGSA MGPV PVSA

savagecounts <- read.table("18-5-24_dedup_Savage_deseq_counts.txt", header = TRUE)

 
#Creating Data matrix 
rownames(savagecounts) <- savagecounts$gene #renames the gene row
savagecounts <- savagecounts %>% dplyr :: select(-"gene") #this gets rid of the name gene in table
coldata <- data.frame(rownames = colnames(savagecounts),
                    reps = as.factor(c(1, 2, 3, 1, 2, 3 ,4,
                                     1, 2 ,3)), 
                    stage = as.factor(c(rep("MG",3),rep("PV",4), rep("SA",3))))

ddsFullCountTable <- DESeqDataSetFromMatrix(
   countData = savagecounts,
   colData = coldata,
   design = ~ reps + stage)
#DESeq2 getting DE genes
savagecounts_dds <- DESeq(ddsFullCountTable )
```

```{r}
########CREATING GSEA LISTS FROM PATHWAY ANALYSIS OF SAV DE GENES
#Comparisons of all 
  #padj filter < 0.01
  #abs(log2fold) filter > 1.5

#MG and SA############################################################################
savageRes_MgSa <- results( savagecounts_dds, contrast = c("stage",  "MG","SA"))
MgSa <- savageRes_MgSa[ which(savageRes_MgSa$padj < 0.01 ), ]
MgSa <- MgSa[which(abs(MgSa$log2FoldChange) > 1.5),]
MgSa$logP <- -log10(MgSa$pvalue)
MgSa$Gene <- rownames(MgSa)
MgSa <- MgSa[which(abs(MgSa$logP) != 0),]
MgSa$metric <- MgSa$logP * abs(MgSa$log2FoldChange)
MgSa_gsea  <- MgSa[,c("Gene","metric")]
gsea_MgSa_df <- data.frame(MgSa_gsea)
gseaDat_MgSa <- filter(gsea_MgSa_df, !is.na(Gene))
ranks_MgSa <- gsea_MgSa_df$metric
names(ranks_MgSa) <- gseaDat_MgSa$Gene
 
#MG and PV############################################################################
savageRes_MgPv <- results( savagecounts_dds ,contrast = c("stage",  "MG","PV"))
MgPv <- savageRes_MgPv[ which(savageRes_MgPv$padj < 0.01 ), ]
MgPv <- MgPv[which(abs(MgPv$log2FoldChange) > 1.5),]
MgPv$logP <- -log10(MgPv$pvalue)
MgPv$Gene <- rownames(MgPv)
MgPv <- MgPv[which(abs(MgPv$logP) != 0),]
MgPv$metric <- MgPv$logP * abs(MgPv$log2FoldChange)
MgPv_gsea  <- MgPv[,c("Gene","metric")]
gsea_MgPv_df <- data.frame(MgPv_gsea)
gseaDat_MgPv <- filter(gsea_MgPv_df, !is.na(Gene))
ranks_MgPv <- gsea_MgPv_df$metric
names(ranks_MgPv) <- gseaDat_MgPv$Gene

#PV and SA############################################################################
savageRes_PvSa <- results( savagecounts_dds ,contrast = c("stage",  "PV","SA"))
PvSa <- savageRes_PvSa[ which(savageRes_PvSa$padj < 0.01 ), ]
PvSa <- PvSa[which(abs(PvSa$log2FoldChange) > 1.5),]
PvSa$logP <- -log10(PvSa$pvalue)
PvSa$Gene <- rownames(PvSa)
PvSa <- PvSa[which(abs(PvSa$logP) != 0),]
PvSa$metric <- PvSa$logP * abs(PvSa$log2FoldChange)
PvSa_gsea  <- PvSa[,c("Gene","metric")]
gsea_PvSa_df <- data.frame(PvSa_gsea)
gseaDat_PvSa <- filter(gsea_PvSa_df, !is.na(Gene))
ranks_PvSa <- gsea_PvSa_df$metric
names(ranks_PvSa) <- gseaDat_PvSa$Gene 
 

```


```{r}
#DESEQ ON SCHULZ
library(readr)
TBcounts <- read.table("18-5-23_Proc_ibet_TC_for_deseq.txt",header = TRUE) %>% dplyr ::select(-ib_3h_1) 
TBcounts <- TBcounts %>% dplyr :: distinct(gene, .keep_all = TRUE) 
#NORMALIZATION BY DESEQ2
rownames(TBcounts) <- TBcounts$gene #renames the gene row
TBcounts <- TBcounts %>% dplyr :: select(-"gene") #this gets rid of the name gene in table
#creating new data frame for DESeq to analyze
tb_new <- data.frame(rownames = colnames(TBcounts),
                     reps = as.factor(c(1,2,3,1,2,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3)),
                    stage = as.factor(c(rep("noo_ib",3), rep("ib_3h", 2), rep("ib_6h",3), rep("ib_12h",3),rep("ib_24h",3),rep("ib_48h",3),rep("ib_3d",3),rep("ib_7d",3),rep("ib_10d",3),rep("ib_14d",3))))
rownames(tb_new) <- tb_new$rownames
tb_new <- tb_new %>% dplyr ::select(-rownames)

##dds stands for the DESeq Data Set
TBcounts <- TBcounts[rowSums(TBcounts) > 0 ,]
ddsFullCountTable <- DESeqDataSetFromMatrix(countData = TBcounts,
                                            colData = tb_new, 
                                            design = ~ reps + stage)

TBcounts_dds <- DESeq(ddsFullCountTable)

#calculating norm counts
##DESeq2 :: allows to specify where this fcn comes from
normDE_counts <- DESeq2::counts(TBcounts_dds, normalized = TRUE) 
normDE_counts_df <- data.frame(normDE_counts)
 

#COMPARING - DE ANALYSIS - FOR GSEA

#comparing stages noo_ib and ib_12h --- the stage of non inhibited bromodomain at time 0 to inhibited bromodomain at time point 12 hours
TBcountsRes <- results( TBcounts_dds ,contrast = c("stage","ib_12h", "noo_ib"))


#resSig stands for the results of the signigicant genes expressed in comparison of noo_ib and ib_6h
resSig <- TBcountsRes[complete.cases(TBcountsRes),]
resSig <- resSig[ which(resSig$padj < 0.01 ), ]
resSig$gene <- rownames(resSig)
resSig$fcsign <- sign(resSig$log2FoldChange) #fcsign stands for the log2foldchange sign

#creating negative and positive logfold change data sets
resSig_log.pos <- resSig[which(resSig$fcsign != -1),]
resSig_log.neg <- resSig[which(resSig$fcsign == -1),]

#GSEA -- MAKING DATA TABLES AND RUNNING FGSEA
  #Making metric rank for 0-12h comparison

#creating metric used for ranking DE of genes for TB schulz 0-12h timepoint contrast
#resSig$fcsign <- sign(resSig$log2FoldChange) #fcsign stands for the log2foldchange sign
#resSig <-  resSig[which(abs(resSig$fcsign) != 0),] #filtering out foldchanges = 0
resSig$logP = -log10(resSig$pvalue) 
resSig <-  resSig[which(abs(resSig$logP) != 0),] 
resSig$metric= resSig$logP * abs(resSig$log2FoldChange)#calculating metric = log10(pvalue)/fcsign
resSig$Gene <- rownames(resSig) #creating column Gene for dataframe
gsea_schulz <-resSig[,c("Gene", "metric")]

#Creating data frame from gsea_schulz for gsea
gsea_schulz_df <- data.frame(gsea_schulz)
rownames(gsea_schulz_df) <- NULL
gsea_schulz_df <- gsea_schulz_df[which(gsea_schulz_df$metric != -Inf),] #removing metric where = -Inf
gsea_schulz_df <- gsea_schulz_df[which(gsea_schulz_df$metric != Inf),]
 
#creating stats and pathways for gsea
gseaDat_schulz <- filter(gsea_schulz_df, !is.na(Gene))
ranks <- gsea_schulz_df$metric
names(ranks) <- gseaDat_schulz$Gene
ranks <- sort(ranks)


#####FOR LOG POS FOLD CHANGE######
#CREATING RANKS AND DATA FRAME FOR GSEA
#resSig_log.pos$fcsign <- sign(resSig_log.pos$log2FoldChange) #fcsign stands for the log2foldchange sign
#resSig_log.pos <-  resSig_log.pos[which(abs(resSig_log.pos$fcsign) != 0),] #filtering out foldchanges = 0
resSig_log.pos$logP = -log10(resSig_log.pos$pvalue) 
resSig_log.pos <-  resSig_log.pos[which(abs(resSig_log.pos$logP) != 0),] 
resSig_log.pos$metric= resSig_log.pos$logP * abs(resSig_log.pos$log2FoldChange) #metric = -log10(pvalue) *abs(log2FoldChange)
resSig_log.pos$Gene <- rownames(resSig_log.pos) #creating column Gene for dataframe
gsea_schulz_log.pos <-resSig_log.pos[,c("Gene", "metric")]
 
  #creating data frame
gsea_schulz_df_log.pos <- data.frame(gsea_schulz_log.pos)
rownames(gsea_schulz_df_log.pos) <- NULL
gsea_schulz_df_log.pos <- gsea_schulz_df_log.pos[which(gsea_schulz_df_log.pos$metric != -Inf),] #removing metric where = -Inf
gsea_schulz_df_log.pos <- gsea_schulz_df_log.pos[which(gsea_schulz_df_log.pos$metric != Inf),]

  #creating ranks for fgsea
gseaDat_schulz_log.pos <- filter(gsea_schulz_df_log.pos, !is.na(Gene))
ranks_log.pos <- gsea_schulz_df_log.pos$metric
names(ranks_log.pos) <- gseaDat_schulz_log.pos$Gene
ranks_log.pos <- sort(ranks_log.pos)

#####FOR LOG NEG FOLD CHANGE######
#CREATING RANKS AND DATA FRAME FOR GSEA
#resSig_log.neg$fcsign <- sign(resSig_log.neg$log2FoldChange) #fcsign stands for the log2foldchange sign
#resSig_log.neg <-  resSig_log.neg[which(abs(resSig_log.neg$fcsign) != 0),] #filtering out foldchanges = 0
resSig_log.neg$logP <-  -log10(resSig_log.neg$pvalue)
resSig_log.neg <-  resSig_log.neg[which(abs(resSig_log.neg$logP) != 0),] 
resSig_log.neg$metric <-  resSig_log.neg$logP * abs(resSig_log.neg$log2FoldChange) #calculating metric = log10(pvalue) 
resSig_log.neg$Gene <- rownames(resSig_log.neg) #creating column Gene for dataframe
gsea_schulz_log.neg <-resSig_log.neg[,c("Gene", "metric")]

  #creating data frame
gsea_schulz_df_log.neg <- data.frame(gsea_schulz_log.neg)
rownames(gsea_schulz_df_log.neg) <- NULL
gsea_schulz_df_log.neg <- gsea_schulz_df_log.neg[which(gsea_schulz_df_log.neg$metric != -Inf),] #removing metric   where = -Inf
gsea_schulz_df_log.neg <- gsea_schulz_df_log.neg[which(gsea_schulz_df_log.neg$metric != Inf),] 
  #creating ranks for fgsea
gseaDat_schulz_log.neg <- filter(gsea_schulz_df_log.neg, !is.na(Gene))
ranks_log.neg <- gsea_schulz_df_log.neg$metric
names(ranks_log.neg) <- gseaDat_schulz_log.neg$Gene
ranks_log.neg <- sort(ranks_log.neg)
 
 

```

```{r}
################################GSEA on all SAV DE genes########################################
####need to make list of all 'pathways'
sav_all_list <- c()
  #for MgSa
MgSa_list <- names(ranks_MgSa)#rownames(MgSa)
  #for MgPv
MgPv_list <- names(ranks_MgPv)#rownames(MgPv)
  #for PvSa
PvSa_list <- names(ranks_PvSa)#rownames(PvSa)
 
#creating full list for all savage 
sav_all_list$MgSa <- MgSa_list
sav_all_list$MgPv <- MgPv_list
sav_all_list$PvSa <- PvSa_list

#FGSEA on SAV DE GENES (NO GO)

fgseaRes_all <- fgsea(pathways = as.list(sav_all_list), stats = ranks, minSize = 1,  nperm = 1000)
fgseaRes_all_pos <- fgsea(pathways = as.list(sav_all_list), stats = ranks_log.pos, minSize = 1,  nperm = 1000)
fgseaRes_all_neg <- fgsea(pathways = as.list(sav_all_list), stats = ranks_log.neg, minSize = 1,  nperm = 1000)
 
##########NEG FOLD CHANGE ENRICHMENT#########
plotEnrichment(pathway = sav_all_list$MgSa,
               stats  = ranks_log.neg) + labs(title = "MgSa neg log fold")
plotEnrichment(pathway = sav_all_list$MgPv,
               stats  = ranks_log.neg) + labs(title ="MgPv neg log fold")
plotEnrichment(pathway = sav_all_list$PvSa,
               stats  = ranks_log.neg) + labs(title ="PvSa neg log fold")
##########POS FOLD CHANGE ENRICHMENT#########
plotEnrichment(pathway = sav_all_list$MgSa,
               stats  = ranks_log.pos) + labs(title ="MgSa pos log fold")
plotEnrichment(pathway = sav_all_list$MgPv,
               stats  = ranks_log.pos) + labs(title ="MgPv pos log fold")
plotEnrichment(pathway = sav_all_list$PvSa,
               stats  = ranks_log.pos) + labs(title ="PvSa pos log fold")
##########TOTAL ENRICHMENT##################
plotEnrichment(pathway = sav_all_list$MgSa,
               stats  = ranks ) + labs(title ="MgSa")
plotEnrichment(pathway = sav_all_list$MgPv,
               stats  = ranks ) + labs(title ="MgPv")
plotEnrichment(pathway = sav_all_list$PvSa,
               stats  = ranks ) + labs(title ="PvSa")

```



```{r}

#######MAKING RANKED METRIC LIST FOR SAVAGE DATA########

#making big data set 'allcomp' with all comparisons to make code easier. Splitting after by 'comparison' 
MGSA_df <- data.frame(Gene = rownames(MgSa), pvalue = MgSa$pvalue, padj = MgSa$padj, comparison = "MgSa",log2FoldChange= MgSa$log2FoldChange)
MGPV_df <- data.frame(Gene = rownames(MgPv), pvalue = MgPv$pvalue, padj = MgPv$padj, comparison = "MgPv", log2FoldChange= MgPv$log2FoldChange)
PVSA_df <- data.frame(Gene = rownames(PvSa), pvalue = PvSa$pvalue, padj = PvSa$padj, comparison = "PvSa",log2FoldChange= PvSa$log2FoldChange)
 
sav_allcomp <- rbind(MGSA_df,MGPV_df, PVSA_df)

#View(gsea_allcomp)

sav_allcomp$logP <- -log10(sav_allcomp$pvalue) #calculating metric == -log10(pvalue)
sav_allcomp <-  sav_allcomp[which(abs(sav_allcomp$logP) != 0),] #filtering out p-values 
sav_allcomp$metric <- sav_allcomp$logP * abs(sav_allcomp$log2FoldChange)
sav_gsea_allcomp <- sav_allcomp[,c("Gene","metric","comparison")]

##filtering out big dataset -- creating data frames for each comparison 
gsea_MgSa_df<- sav_gsea_allcomp %>% filter(comparison == "MgSa") %>% dplyr :: select(-comparison) 
gsea_MgPv_df <- sav_gsea_allcomp %>% filter(comparison == "MgPv") %>% dplyr :: select(-comparison) 
gsea_PvSa_df <- sav_gsea_allcomp %>% filter(comparison == "PvSa") %>% dplyr :: select(-comparison) 
 
#creating stats and pathways for gsea
  #MgSa
gseaDat_MgSa <- filter(gsea_MgSa_df, !is.na(Gene))
ranks_MgSa <- gsea_MgSa_df$metric
names(ranks_MgSa) <- gseaDat_MgSa$Gene
ranks_MgSa <- sort(ranks_MgSa)
  #MgPv
gseaDat_MgPv <- filter(gsea_MgPv_df, !is.na(Gene))
ranks_MgPv <- gsea_MgPv_df$metric
names(ranks_MgPv) <- gseaDat_MgPv$Gene
ranks_MgPv <- sort(ranks_MgPv)
#PvSa
gseaDat_PvSa <- filter(gsea_PvSa_df, !is.na(Gene))
ranks_PvSa <- gsea_PvSa_df$metric
names(ranks_PvSa) <- gseaDat_PvSa$Gene
ranks_PvSa <- sort(ranks_PvSa)

#####FOR LOG POS FOLD CHANGE######
#CREATING RANKS AND DATA FRAME FOR GSEA
#resSig_log.pos$fcsign <- sign(resSig_log.pos$log2FoldChange) #fcsign stands for the log2foldchange sign
#resSig_log.pos <-  resSig_log.pos[which(abs(resSig_log.pos$fcsign) != 0),] #filtering out foldchanges = 0
 
```
 

```{r}
############################FGSEA ON 2019 CLUSTERS#############################
#In order to answer the biological questions of our data, we need to take statisitcal steps to gather information in order to prove, or answer the hypothesis at hand. Clustering our data is an example of this method. Here we are taking the fuzzy cluster GO analysis results, and preparing them for GSEA pipeline. 

#Reading in huge file with all GO terms of cluster.s 
fuzzyClust <- read.table("fuzzyclusters_GO.tab") %>% dplyr :: select(Name, Result.gene.list, Cluster,Type)
fuzzyClust$Result.gene.list <- gsub(',',',',fuzzyClust$Result.gene.list,fixed=TRUE)
fuzzyClust$Result.gene.list <- strsplit(fuzzyClust$Result.gene.list, ",")
 

#cluster1 <- data.frame(GO[1]) %>%dplyr::select(Cluster1.Name,Cluster1.Result.gene.list,Cluster1.Type) 
#cluster1$Cluster1.Result.gene.list <- gsub(',',',',cluster1$Cluster1.Result.gene.list,fixed=TRUE)
#cluster1$Cluster1.Result.gene.list <- strsplit(cluster1$Cluster1.Result.gene.list, ",")

cluster1_bio <- fuzzyClust %>% filter(Type == "Biological Process", Cluster == 1)
clust1_bio_list <- as.list(cluster1_bio)
names(clust1_bio_list$Result.gene.list) <- clust1_bio_list$Name
clust1_bio <- as.list(clust1_bio_list$Result.gene.list)
#View(clust1_bio)

cluster1_cell <- fuzzyClust %>% filter(Type == "Cellular Component", Cluster == 1)
clust1_cell_list <- as.list(cluster1_cell)
names(clust1_cell_list$Result.gene.list) <- clust1_cell_list$Name
clust1_cell <- clust1_cell_list$Result.gene.list
#View(fuzzylist_1_cell)

cluster1_mol <- fuzzyClust %>% filter(Type == "Molecular Function",Cluster == 1)
clust1_mol_list <- as.list(cluster1_mol)
names(clust1_mol_list$Result.gene.list) <- clust1_mol_list$Name
clust1_mol <- clust1_mol_list$Result.gene.list

#########CLUSTER 2######### 
 
cluster2_bio <- fuzzyClust %>% filter(Type == "Biological Process", Cluster == 2)
clust2_bio_list <- as.list(cluster2_bio)
names(clust2_bio_list$Result.gene.list) <- clust2_bio_list$Name
clust2_bio <- clust2_bio_list$Result.gene.list
#View(clust2_bio)

cluster2_cell <- fuzzyClust %>% filter(Type == "Cellular Component", Cluster == 2)
clust2_cell_list <- as.list(cluster2_cell)
names(clust2_cell_list$Result.gene.list) <- clust2_cell_list$Name
clust2_cell <- clust2_cell_list$Result.gene.list
#View(fuzzylist_2_cell)

#clust2_mol <- cluster2 %>% filter(Cluster2.Type == "Molecular Function")
#clust2_mol_list <- as.list(clust2_mol)
#names(clust2_mol_list$Cluster2.Result.gene.list) <- clust2_mol_list$Cluster2.Name
#fuzzylist_2_mol <- clust2_mol_list$Cluster2.Result.gene.list
#View(fuzzylist_2_mol)

#cluster3 <- data.frame(GO[3])%>%dplyr::select(Cluster3.Name,Cluster3.Result.gene.list,Cluster3.Type) 
#clust3_bio <- cluster3 %>% filter(Cluster3.Type == "Biological Process")
#clust3_cell <- cluster3 %>% filter(Cluster3.Type == "Cellular Component")
#clust3_mol <- cluster3 %>% filter(Cluster3.Type == "Molecular Function")

cluster4_bio <- fuzzyClust %>% filter(Type == "Biological Process", Cluster == 4)
clust4_bio_list <- as.list(cluster4_bio)
names(clust4_bio_list$Result.gene.list) <- clust4_bio_list$Name
clust4_bio <- clust4_bio_list$Result.gene.list
#View(fuzzylist_4_bio)

cluster4_cell <- fuzzyClust %>% filter(Type == "Cellular Component", Cluster == 4)
clust4_cell_list <- as.list(cluster4_cell)
names(clust4_cell_list$Result.gene.list) <- clust4_cell_list$Name
clust4_cell <- clust4_cell_list$Result.gene.list
#View(fuzzylist_4_cell)

cluster4_mol <- fuzzyClust %>% filter(Type == "Molecular Function", Cluster == 4)
clust4_mol_list <- as.list(cluster4_mol)
names(clust4_mol_list$Result.gene.list) <- clust4_mol_list$Name
clust4_mol <- clust4_mol_list$Result.gene.list
#View(clust4_mol)
#cluster5 <- data.frame(GO[5])%>%dplyr::select(Cluster5.Name,Cluster5.Result.gene.list,Cluster5.Type) 
#clust5_bio <- cluster5 %>% filter(Cluster5.Type == "Biological Process")
#clust5_cell <- cluster5 %>% filter(Cluster5.Type == "Cellular Component")
#clust5_mol <- cluster5 %>% filter(Cluster5.Type == "Molecular Function")
 

#clust6_bio <- cluster6 %>% filter(Cluster6.Type == "Biological Process")
cluster6_cell <- fuzzyClust %>% filter(Type == "Cellular Component", Cluster == 6) 
clust6_cell_list <- as.list(cluster6_cell)
names(clust6_cell_list$Result.gene.list) <- clust6_cell_list$Name
clust6_cell <- clust6_cell_list$Result.gene.list

#making Result.gene.list entry into list 
 
all_fuzzy <- c()
all_fuzzy$bio1 <-  clust1_bio 
all_fuzzy$bio2 <- clust2_bio
all_fuzzy$bio4 <- clust4_bio
#all_fuzzy$bio6 <- clust6_bio

all_fuzzy$cell1 <- clust1_cell
all_fuzzy$cell2 <- clust2_cell
all_fuzzy$cell4 <- clust4_cell
all_fuzzy$cell6 <- clust6_cell

all_fuzzy$mol1 <- clust1_mol
#all_fuzzy$mol2 <- clust2_mol
all_fuzzy$mol4 <- clust4_mol
#all_fuzzy$mol6 <- clust6_mol
 
#View(all_fuzzy)
#library(fgsea)
```

```{r}
 
exampleRanks
fgsea_mgsa_fuzzy <- c()
fgsea_mgpv_fuzzy <- c()
fgsea_pvsa_fuzzy <- c()
 

temp <- BiocParallel::bplapply(X = as.list(all_fuzzy[[1]]), FUN = fgsea::fgsea, stats = ranks_MgSa, minSize = 1,  nperm = 2)
temp2 <- fgsea(as.list(all_fuzzy$bio1), ranks_MgSa, minSize = 1, nperm = 10)

length(intersect(clust1_biopath[[1]], names(ranks_MgSa)))
 examplePathways
str(clust1_bio)
#for (i in 1:9){
#fgsea_mgsa_fuzzy[[i]] = bplapply(c(as.list(all_fuzzy[[i]]),ranks_MgSa, minSize = 1,  nperm = 100), fgsea, BPPARAM = SnowParam())
#fgsea_mgpv_fuzzy[[i]] = bplapply(c(as.list(all_fuzzy[[i]]),ranks_MgPv, minSize = 1,  nperm = 100), fgsea, BPPARAM = SnowParam())
#fgsea_pvsa_fuzzy[[i]] = bplapply(c(as.list(all_fuzzy[[i]]),ranks_PvSa, minSize = 1,  nperm = 100), fgsea, BPPARAM = SnowParam())
#}

#ranks_MgSa
#names(fgsea_mgsa_fuzzy) <- names(all_fuzzy)
#names(fgsea_mgpv_fuzzy) <- names(all_fuzzy)
#names(fgsea_pvsa_fuzzy) <- names(all_fuzzy)
#View(fgsea_mgsa_fuzzy)
#View(fgsea_mgpv_fuzzy)
#View(fgsea_pvsa_fuzzy)

 

#head(ranks_MgSa)
#head(exampleRanks)
#all_fuzzy$cell1
#length(ranks_PvSa)
c <- intersect((clust1_bio$`movement of cell or subcellular component`), names(ranks_MgPv))
length(c)
length(clust1_bio$`movement of cell or subcellular component`)

 
```

 