---
title: "stoebel_DESeq_edgeR"
author: "Lian Morales"
date: "6/26/2019"
output: html_document
---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library("dplyr")
library("tidyr")
library("DESeq2")
library("edgeR")
library(readr)
ec_rawcounts <- read.table("LB_Time_Course_GCA_000005845.2_ASM584v2_genomic_counts.txt",header = TRUE)
 
```


```{r}
#format data for normalization

ec_rawcounts_norm <- ec_rawcounts

rownames(ec_rawcounts_norm) <- ec_rawcounts_norm$Geneid

ec_rawcounts_norm <- ec_rawcounts_norm %>% dplyr::select(-Geneid)

ec_coldata <- data.frame(names = colnames(ec_rawcounts_norm)) %>%
  separate(names, c("treat", "rep_time"), "_") %>%
  mutate(rep = ifelse(substr(rep_time,start=1,stop = 1) == "A", 1, 
                        ifelse(substr(rep_time,start=1,stop = 1) == "B", 2, 3))) %>%
  mutate(time = ifelse(substr(rep_time,start=3,stop = 3) == "1", 0,
                      ifelse(substr(rep_time,start=3,stop = 3) == "2", 30,
                             ifelse(substr(rep_time,start=3,stop = 3) == "3", 60,
                                    ifelse(substr(rep_time,start=3,stop = 3) == "4", 90,
                                           ifelse(substr(rep_time,start=3,stop = 3) == "5", 120, 150)))))) %>%
  
  mutate(treat = ifelse(treat == "JH01", "WT","dRpoS")) %>%
  mutate(timetreat = paste(treat,time,sep = "")) %>%
  select(-rep_time)
rownames(ec_coldata) <- colnames(ec_rawcounts_norm)
 
ec_coldata
```


```{r}
#####DESEQ FOR CONT DATA

#ec_dds <- DESeqDataSetFromMatrix(ec_rawcounts_norm, colData = ec_coldata, design = ~time + treat)

#ec_dds_de <- DESeq(ec_dds)
#ec_dds_de

#Calculating Raw Counts
#ec_norm_counts <- data.frame(counts(ec_dds_de, normalized = TRUE)) %>%
 # mutate(Geneid = rownames(ec_rawcounts_norm))


```



```{r}
#COMPARING - DE ANALYSIS - getting DE genes

#looking at WT continuous
#ECcountsRes <- results(ec_dds_de, name = "time")
#length(rownames(ECcountsRes))
#ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
#WT_cont <- ECresSig
#length(WT_cont)

ec_dds <- DESeqDataSetFromMatrix(ec_rawcounts_norm, colData = ec_coldata, design = ~timetreat)
ec_dds_de <- DESeq(ec_dds)

#looking at WT0  to WT30
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT0", "WT30"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT0_WT30 <- ECresSig


#looking at WT0  to WT60
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT0", "WT60"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT0_WT60 <- ECresSig


#looking at WT0  to WT90
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT0", "WT90"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT0_WT90 <- ECresSig



#looking at WT0  to WT120
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT0", "WT120"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT0_WT120 <- ECresSig


#looking at WT0  to WT150
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT0", "WT150"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT0_WT150 <- ECresSig


length(rownames(WT0_WT150))
#############
#############

#looking at drpos0  to drpos30
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "dRpoS0", "dRpoS30"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
dRpoS0_dRpoS30 <- ECresSig


#looking at KO0  to KO60
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "dRpoS0", "dRpoS60"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
dRpoS0_dRpoS60 <- ECresSig
length(dRpoS0_dRpoS60)


#looking at KO0  to KO90
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "dRpoS0", "dRpoS90"))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
dRpoS0_dRpoS90 <- ECresSig


#looking at KO0  to KO150
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "dRpoS0", "dRpoS150"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
dRpoS0_dRpoS50 <- ECresSig

#############
#############

#looking at WT30 drpos30
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT30", "dRpoS30"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT30_dRpoS30 <- ECresSig


#looking at WT60 drpos60
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT60", "dRpoS60"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT60_dRpoS60 <- ECresSig


#looking at WT90 drpoS90
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT90", "dRpoS90"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT90_dRpoS90 <- ECresSig


#looking at WT120 drpoS120
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT120", "dRpoS120"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT120_dRpoS120 <- ECresSig


#looking at WT150 drpos150
ECcountsRes <- results(ec_dds_de, contrast = c("timetreat", "WT150", "dRpoS150"))
length(rownames(ECcountsRes))
ECresSig <- ECcountsRes[ which(ECcountsRes$padj < 0.01 ), ]
WT150_dRpoS150 <- ECresSig

```

```{r}
#making venn diagram
library(VennDiagram)

#area_WT_cont <- length(rownames(WT_cont))
area_WT0_WT150 <- length(rownames(WT0_WT150))
area_dRpoS0_dRpoS50 <- length(rownames(dRpoS0_dRpoS50))
area_dRpoS0_dRpoS90 <- length(rownames(dRpoS0_dRpoS90))
area_WT0_WT90 <- length(rownames(WT0_WT90))
area_WT90_WT150 <- length(rownames(WT90_WT150))
area_dRpoS90_dRpoS150 <- length(rownames(dRpoS90_dRpoS150))
area_dRpoS0_dRpoS60 <- length(rownames(dRpoS0_dRpoS60))
area_WT0_WT60 <- length(rownames(WT0_WT60))
area_WT150_dRpoS150 <- length(rownames(WT150_dRpoS150))
area_WT0_WT30 <- length(rownames(WT0_WT30))
area_dRpoS0_dRpoS30 <- length(rownames(dRpoS0_dRpoS30))
area_WT30_dRpoS30 <- length(rownames(WT30_dRpoS30))
area_WT60_dRpoS60 <- length(rownames(WT60_dRpoS60))
area_WT90_dRpoS90 <- length(rownames(WT90_dRpoS90))
area_WT120_dRpoS120 <- length(rownames(WT120_dRpoS120))
area_WT0_WT120 <- length(rownames(WT0_WT120))
 
#looking at comparing "WT0_WT30" to "WT30_dRpoS30"
cross_0_30 <- length(intersect(rownames(WT0_WT30),rownames(WT30_dRpoS30)))
grid.newpage()
draw.pairwise.venn(area1= area_WT0_WT30, area2 = area_WT30_dRpoS30, cross.area = cross_0_30, category = c("WT0_WT30","WT30_dRpoS30"),lty = rep("blank",2),fill = c("light blue", "light green"))

cross_0_30_list <- intersect(rownames(WT0_WT30),rownames(WT30_dRpoS30))


#looking at comparing "WT0_WT60" to "dRpoS0_dRpoS60"
cross_0_60 <- length(intersect(rownames(WT0_WT60),rownames(WT60_dRpoS60)))
grid.newpage()
draw.pairwise.venn(area1= area_WT0_WT60, area2 = area_WT60_dRpoS60, cross.area = cross_0_60, category = c("WT0_WT60","WT60_dRpoS60"),lty = rep("blank",2),fill = c("light blue", "light green"))
 
cross_0_60_list <- intersect(rownames(WT0_WT60),rownames(WT60_dRpoS60))

#looking at comparing "WT0_WT90" to "WT90_dRpoS90"
cross_0_90 <- length(intersect(rownames(WT0_WT90),rownames(WT90_dRpoS90)))
grid.newpage()
draw.pairwise.venn(area1= area_WT0_WT90, area2 = area_WT90_dRpoS90, cross.area = cross_0_90, category = c("WT0_WT90","WT90_dRpoS90"),lty = rep("blank",2),fill = c("light blue", "light green"))

cross_0_90_list <- intersect(rownames(WT0_WT90),rownames(WT90_dRpoS90))

#looking at comparing "WT0_WT120" to "WT120_dRpoS120"
cross_0_120 <- length(intersect(rownames(WT0_WT120),rownames(WT120_dRpoS120)))
grid.newpage()
draw.pairwise.venn(area1= area_WT0_WT120, area2 = area_WT120_dRpoS120, cross.area = cross_0_120, category = c("WT0_WT120","WT120_dRpoS120"),lty = rep("blank",2),fill = c("light blue", "light green"))

cross_0_120_list <- intersect(rownames(WT0_WT120),rownames(WT120_dRpoS120))

#looking at comparing "WT0_WT150" to "WT150_dRpoS150"
cross_0_150 <- length(intersect(rownames(WT0_WT150),rownames(WT150_dRpoS150)))
grid.newpage()
draw.pairwise.venn(area1= area_WT0_WT150, area2 = area_WT150_dRpoS150, cross.area = cross_0_150, category = c("WT0_WT150","WT150_dRpoS150"),lty = rep("blank",2),fill = c("light blue", "light green"))
cross_0_150_list <- intersect(rownames(WT0_WT150),rownames(WT150_dRpoS150))





#looking at comparing "WT0_WT150","WT0_WT90","WT0_WT60"

cross12 <- length(intersect(rownames(WT150_dRpoS150),rownames(WT90_dRpoS90)))
cross23 <- length(intersect(rownames(WT90_dRpoS90),rownames(WT60_dRpoS60)))
cross123 <- length(intersect(intersect(rownames(WT150_dRpoS150),rownames(WT60_dRpoS60)),rownames(WT90_dRpoS90)))
cross13 <- length(intersect(rownames(WT150_dRpoS150),rownames(WT60_dRpoS60)))

# Note to Lian:  cross13 doesn't exist ... should it be one more comparison above?
#"WT150_dRpoS150","WT90_dRpoS90","WT60_dRpoS60"
grid.newpage() 


draw.triple.venn(area1 = area1, area2 = area4, area3 = area8,n12 = cross12, n23 = cross23, n13 = cross13,n123 = cross123, category = c("WT150_dRpoS150","WT90_dRpoS90","WT60_dRpoS60") ,lty = "blank",fill = c("skyblue", "pink1", "mediumorchid")) 
```
 


 
```{r}
##making columns of rownames of DE genes across 9 comparisons
gene_interest <- read.table("genesOfInterest.txt", header = TRUE)
colnames(gene_interest)
colnames(gene_interest)[1] <- "genename"

#WT_cont_DF <- data.frame(geneID = rownames(WT_cont), comparison = "WT_cont")
WT0_WT30_DF <- data.frame(geneID = rownames(WT0_WT30), comparison = "WT0_WT30")
WT0_WT60_DF <- data.frame(geneID = rownames(WT0_WT60), comparison = "WT0_WT60")
WT0_WT90_DF<- data.frame(geneID = rownames(WT0_WT90), comparison = "WT0_WT90")
WT0_WT120_DF<- data.frame(geneID = rownames(WT0_WT120), comparison = "WT0_WT120")
WT0_WT150_DF <- data.frame(geneID = rownames(WT0_WT150), comparison = "WT_WT150")

WT30_dRpoS30_DF <- data.frame(geneID = rownames(WT30_dRpoS30), comparison = "WT30_dRpoS30")
WT60_dRpoS60_DF <- data.frame(geneID = rownames(WT60_dRpoS60), comparison = "WT60_dRpoS60")

WT90_dRpoS90_DF <- data.frame(geneID = rownames(WT90_dRpoS90), comparison = "WT90_dRpoS90")
WT120_dRpoS120_DF <- data.frame(geneID = rownames(WT120_dRpoS120), comparison = "WT150_dRpoS150")
WT150_dRpoS150_DF <- data.frame(geneID = rownames(WT150_dRpoS150), comparison = "WT150_dRpoS150")

rownames(WT0_WT30)

allDEcomp <- rbind(WT0_WT30_DF,WT0_WT60_DF,WT0_WT90_DF,WT0_WT120_DF,WT150_dRpoS150_DF,WT30_dRpoS30_DF,WT60_dRpoS60_DF,WT90_dRpoS90_DF,WT120_dRpoS120_DF,WT150_dRpoS150_DF)


#copying all DEs from comparisons. 
colnames(allDEcomp)[1] <- "Geneid" #renaming the geneID to Geneid
ec_Counts_join <- ec_Counts %>% dplyr::select(  "Geneid", "bnum" ,"genename" )
allDEcomp <- allDEcomp %>% left_join(ec_Counts_join, by.x = Geneid, by.y = bnum) %>%
 select(Geneid, comparison, genename,bnum)
#######
#making data frame matching all genes of interest (GOI for genes of interest)
allDEcomp_GOI <- allDEcomp %>% left_join(gene_interest, by.x = genename) %>%
 select(Geneid, comparison, genename,bnum, group)


#######################
#######################
#making list of all crosses
cross_0_30_list_DF <- data.frame(geneID = cross_0_30_list, comparison = "WT0_WT30.WT30_dRpoS30")
cross_0_60_list_DF <- data.frame(geneID = cross_0_60_list, comparison = "WT0_WT60.WT60_dRpoS60")
cross_0_90_list_DF <- data.frame(geneID = cross_0_90_list, comparison = "WT0_WT90.WT90_dRpoS90")
cross_0_120_list_DF <- data.frame(geneID = cross_0_120_list, comparison = "WT0_WT120.WT120_dRpoS120")
cross_0_150_list_DF <- data.frame(geneID = cross_0_150_list, comparison = "WT0_WT150.WT150_dRpoS150")

crossDEcomp <- rbind(cross_0_30_list_DF, cross_0_60_list_DF,cross_0_90_list_DF,cross_0_120_list_DF,cross_0_150_list_DF)

colnames(crossDEcomp)[1] <- "Geneid" #renaming the geneID to Geneid
ec_Counts_join <- ec_Counts %>% dplyr::select(  "Geneid", "bnum" ,"genename" )
crossDEcomp <- crossDEcomp %>% left_join(ec_Counts_join, by.x = Geneid, by.y = bnum) %>%
 select(Geneid, comparison, genename, bnum)

#joining the genes of interest list by group of insensitive to this list
crossDEcomp_GOI <- crossDEcomp %>% left_join(gene_interest, by.x = genename) %>%
 select(Geneid, comparison, genename,bnum, group)

###############################
###############################
#making genelist of all intersct of all crossed genes
cross_intersect <- Reduce(intersect,list(cross_0_30_list,cross_0_60_list,cross_0_90_list,cross_0_120_list,cross_0_150_list))

inter_crossDEcomp <- data.frame(geneID = cross_intersect, comparison = "allCross")

colnames(inter_crossDEcomp)[1] <- "Geneid" #renaming the geneID to Geneid
ec_Counts_join <- ec_Counts %>% dplyr::select(  "Geneid", "bnum" ,"genename" )
inter_crossDEcomp <- inter_crossDEcomp %>% left_join(ec_Counts_join, by.x = Geneid, by.y = bnum) %>%
 select(Geneid, comparison, genename, bnum)

#putting in the genes of interest into table
inter_crossDEcomp_GOI <- inter_crossDEcomp %>% left_join(gene_interest, by.x = genename, by.y = bnum) %>%
 select(Geneid, comparison, genename, bnum,group)

write_csv(allDEcomp,"allDEcomp.csv")
write_csv(crossDEcomp,"crossDEcomp.csv")
write_csv(inter_crossDEcomp,"inter_crossDEcomp.csv")
write_csv(allDEcomp_GOI,"allDEcomp_GOI.csv")
write_csv(crossDEcomp_GOI,"crossDEcomp_GOI.csv")
write_csv(inter_crossDEcomp_GOI,"inter_crossDEcomp_GOI.csv")

```
